/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.hornetsa.view.motorcycle;

import org.hornetsa.IIntersetedGUI;
import org.hornetsa.Main;
import org.hornetsa.model.Motorcycle;
import org.hornetsa.services.VehicleService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

/**
 *
 * @author jaime
 */
public class GUIListMotorcycle extends javax.swing.JFrame implements IIntersetedGUI {

    /**
     * Creates new form GUIListMotorcycle
     */

    VehicleService vehicleService;

    public GUIListMotorcycle(VehicleService vehicleService) {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Hornet Corsair | List Motorcycle");
        setSize(800, 500);
        setIconImage(new ImageIcon(Main.class.getClassLoader().getResource("img/favicon.png")).getImage());
        this.vehicleService = vehicleService;
        vehicleService.addGUIInterested(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        LblTitle = new javax.swing.JLabel();
        btnList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMotorcycles = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitle.setText("List Motorcycle");

        btnList.setText("List");
        btnList.setBackground(Color.BLACK);
        btnList.setForeground(Color.WHITE);

        jTableMotorcycles.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {
                        "Id", "Brand", "Price", "Model", "Abs", "ForkType", "HelmetIncluded"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                    false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMotorcycles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(352, 352, 352)
                                                                .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(149, 149, 149)
                                                                .addComponent(LblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 145, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(LblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>




    // Variables declaration - do not modify
    private javax.swing.JLabel LblTitle;
    private javax.swing.JButton btnList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMotorcycles;
    // End of variables declaration

    public JButton getBtnList() {
        return btnList;
    }

    public JTable getTable() {
        return jTableMotorcycles;
    }

    @Override
    public void changeTable() {
        DefaultTableModel model = (DefaultTableModel) getTable().getModel();
        model.setRowCount(0);
        List<Motorcycle> motorcycles = vehicleService.getMotorcyclesList();

        for (Motorcycle motorcycle : motorcycles) {
            Object[] rowData = {
                    motorcycle.getIdVehicle(),
                    motorcycle.getBrand(),
                    motorcycle.getPrice(),
                    motorcycle.getModel(),
                    motorcycle.isAbs(),
                    motorcycle.getForkType(),
                    motorcycle.isHelmetIncluded()
            };
            model.addRow(rowData);
        }
    }

    @Override
    public void dispose() {
        vehicleService.removeGUIInterested(this);
        super.dispose();
    }
}
